version: '3.7'

services:
  appDB:
      image: postgres:15.2
      restart: always
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      ports:
        - '5431:5432'
      volumes:
        - ./postgres-data:/var/lib/postgresql/data
        - ./AppDB/init.sql:/docker-entrypoint-initdb.d/init.sql

#  collector:
#    image: collector
#    ports:
#      - 8080:8080
#    environment:
#      RABBITMQ_EXCHANGE: ws1
#      RABBITMQ_QUEUES: humidity,temperature,heat index,wind speed,wind direction,pressure,day,rain quantity
#    restart: on-failure
#    depends_on:
#      - rabbitmq
